add status check job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,11 +31,25 @@ jobs:
         run: |
           ./gradlew :buildAckpine --stacktrace
 
+  status-check:
+    runs-on: ubuntu-latest
+    if: always()
+    needs: [ build ]
+
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ "{{" }} toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+
   publish:
     name: Upload artifacts
     runs-on: ubuntu-latest
     if: github.repository == 'solrudev/Ackpine' && github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
-    needs: [ build ]
+    needs: [ status-check ]
 
     steps:
       - name: Checkout
@@ -62,7 +76,7 @@ jobs:
     name: Publish documentation
     runs-on: ubuntu-latest
     if: github.repository == 'solrudev/Ackpine' && github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == true
-    needs: [ build ]
+    needs: [ status-check ]
 
     permissions:
       contents: write
